Update motivation.md in KOR
facebookexperimental/Recoil pull request #1003
Opened 2021-05-02 14:47 UTC by nightohl

It was modified to make it more natural to interpret in Korean.

2021-05-03 21:39 UTC, jinsoo601 requested changes

2021-05-03 21:39 UTC, jinsoo601 commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/motivation.md
> +- 우리는 shared state도 React의 local state처럼 간단한 get/set 인터페이스로 사용할 수 있도록 boilerplate-free API를 제공한다.(필요한 경우 reducers 등으로 캡슐화할 수도 있다.)
shared state -> 공유 상태
local state -> 컴포넌트 내부 상태

2021-05-04 03:14 UTC, nightohl commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/motivation.md
> +- 우리는 shared state도 React의 local state처럼 간단한 get/set 인터페이스로 사용할 수 있도록 boilerplate-free API를 제공한다.(필요한 경우 reducers 등으로 캡슐화할 수도 있다.)
현재 한글 문서에는 : 
> 우리는 공유되는 상태가 React 내부 상태와 동일한 간단한 ... 

라고 쓰여있는데, 처음에 저는 무슨 말인지 한번에 이해가 되지 않아서 원문을 보고 확 와닿았던 기억이 있습니다.
shared state <-> local state가 대조된다는 것이 명확하게 보였으면 싶어서 저 부분은 원문의 단어 그대로 가져가는게 어떨까 싶었습니다.

> 우리는 공유상태도 React의 컴포넌트의 내부 상태처럼 간단한 get/set 인터페이스로 ...
로 번역하는 것도 좋은 것 같습니다.

혹시 첫번째 의견에 대해서는 어떻게 생각하시는지 여쭤봐도 될까요?

2021-05-04 15:26 UTC, jinsoo601 commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/motivation.md
> +- 우리는 shared state도 React의 local state처럼 간단한 get/set 인터페이스로 사용할 수 있도록 boilerplate-free API를 제공한다.(필요한 경우 reducers 등으로 캡슐화할 수도 있다.)
아아 의도가 있으셨군요. 그래도 혹시 영어가 힘드신 분들이 읽으실 수도 있으니까,
`우리는 shared state(공유상태)도 React의 local state(내부상태)처럼 간단한 get/set 인터페이스로... `
이렇게 원문 + 괄호안에 번역된 표현 같이 가져가는건 어떨까요?

2021-05-05 01:00 UTC, nightohl commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/motivation.md
> +- 우리는 shared state도 React의 local state처럼 간단한 get/set 인터페이스로 사용할 수 있도록 boilerplate-free API를 제공한다.(필요한 경우 reducers 등으로 캡슐화할 수도 있다.)
> 우리는 공유상태(shared state)도 React의 내부상태(local state)처럼 간단한 get/set 인터페이스로 ...

로 최종 반영하겠습니다. 감사합니다.

2021-05-05 14:55 UTC, jinsoo601 approved these changes

2021-05-06 06:22 UTC, merged