Update installation.md in KOR
facebookexperimental/Recoil pull request #1004
Opened 2021-05-02 15:48 UTC by nightohl

Translate content and modify it for more natural interpretation in Korean.

2021-05-03 21:32 UTC, jinsoo601 requested changes

2021-05-03 21:32 UTC, jinsoo601 commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/installation.md
> +또는 <a href="https://classic.yarnpkg.com/en/docs/install/" target="_blank">yarn</a>을 사용한다면 :
: 전에 white space 빼주세요!

2021-05-03 21:32 UTC, jinsoo601 commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/installation.md
> +Recoil 패키지는 <a href="https://www.npmjs.com/get-npm" target="_blank">npm</a>에 존재한다. 안정화된 최신 버전을 설치하려면 아래의 명령어를 실행하자.
Official Doc이라서 ...다로 끝나는 문장을 선호하고 있습니다.

2021-05-03 21:32 UTC, jinsoo601 commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/installation.md
> +프로젝트에서 [eslint-plugin-react-hooks](https://www.npmjs.com/package/eslint-plugin-react-hooks)을 사용하는 경우. 예를 들어 다음과 같이 eslint 설정을 사용하는 경우 :
: 앞의 white space 빼주세요!

2021-05-03 21:32 UTC, jinsoo601 commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/installation.md
> +[`'useRecoilCallback'`](docs/api-reference/core/useRecoilCallback)을 `additionalHooks` 목록에 추가하는 것이 좋다. 이 변경으로 인해 ESLint는 `useRecoilCallback()`을 사용하기 위해 전달된 종속성이 잘못 지정되었을 때 이를 경고하고 해결 방법을 제안한다. `additi
이 변경으로 인해 -> 이를 추가할 경우,

2021-05-03 21:32 UTC, jinsoo601 commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/installation.md
> +  또는 `package.json` 파일에 종속성을 추가한 뒤, `npm install` 또는 `yarn` 명령어를 실행하자 :
마찬가지로 ...다로 끝나는 문장을 선호합니다!

2021-05-03 21:42 UTC, jinsoo601 commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/installation.md
> +현재의 `master` 브랜치에 기반하여 매일 한 번씩 패키지를 빌드하고 GitHub에 `nightly` 브랜치로 게시한다. 아래의 `npm` 명령어를 통해 `nightly` 브랜치를 이용할 수 있다.
로 게시한다 -> 에 배포된다.

2021-05-04 02:32 UTC, nightohl commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/installation.md
> +  또는 `package.json` 파일에 종속성을 추가한 뒤, `npm install` 또는 `yarn` 명령어를 실행하자 :
명령어를 실행하면 된다:
로 수정하겠습니다.

2021-05-04 02:40 UTC, nightohl commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/installation.md
> +현재의 `master` 브랜치에 기반하여 매일 한 번씩 패키지를 빌드하고 GitHub에 `nightly` 브랜치로 게시한다. 아래의 `npm` 명령어를 통해 `nightly` 브랜치를 이용할 수 있다.
'publish'를 '배포한다'로 해석하는 것은 좋다고 생각합니다.

1. 우리는 매일 한 번씩 현재의 `master` 브랜치에 기반하여 패키지를 빌드하고 GitHub에 `nightly` 브랜치로 배포한다.
2. 매일 한번씩 현재의 `master` 브랜치에 기반하여 패키지가 빌드되고 GitHub에 `nightly` 브랜치로 배포된다.

수동의 의미로 적으려면 2번처럼 바꾸는 것이 맞을 것 같고, 원문에 가까운 것은 1번인 것 같은데 의견주신 '배포한다'로 해석하는 것을 반영하여 1번으로 수정하는 것은 어떠신가요?

2021-05-04 02:40 UTC, nightohl commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/installation.md
> +[`'useRecoilCallback'`](docs/api-reference/core/useRecoilCallback)을 `additionalHooks` 목록에 추가하는 것이 좋다. 이 변경으로 인해 ESLint는 `useRecoilCallback()`을 사용하기 위해 전달된 종속성이 잘못 지정되었을 때 이를 경고하고 해결 방법을 제안한다. `additi
오..! '이를 추가하면' 으로 바꾸는 것은 어떨까요?

2021-05-04 02:40 UTC, nightohl commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/installation.md
> +프로젝트에서 [eslint-plugin-react-hooks](https://www.npmjs.com/package/eslint-plugin-react-hooks)을 사용하는 경우. 예를 들어 다음과 같이 eslint 설정을 사용하는 경우 :
수정하겠습니다.

2021-05-04 02:40 UTC, nightohl commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/installation.md
> +또는 <a href="https://classic.yarnpkg.com/en/docs/install/" target="_blank">yarn</a>을 사용한다면 :
수정하겠습니다.

2021-05-04 02:40 UTC, nightohl commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/installation.md
> +Recoil 패키지는 <a href="https://www.npmjs.com/get-npm" target="_blank">npm</a>에 존재한다. 안정화된 최신 버전을 설치하려면 아래의 명령어를 실행하자.
'실행하면 된다.' 로 다시 되돌리면 될 거 같습니다.

2021-05-04 15:20 UTC, jinsoo601 commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/installation.md
> +[`'useRecoilCallback'`](docs/api-reference/core/useRecoilCallback)을 `additionalHooks` 목록에 추가하는 것이 좋다. 이 변경으로 인해 ESLint는 `useRecoilCallback()`을 사용하기 위해 전달된 종속성이 잘못 지정되었을 때 이를 경고하고 해결 방법을 제안한다. `additi
좋습니다!

2021-05-04 15:20 UTC, jinsoo601 commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/installation.md
> +현재의 `master` 브랜치에 기반하여 매일 한 번씩 패키지를 빌드하고 GitHub에 `nightly` 브랜치로 게시한다. 아래의 `npm` 명령어를 통해 `nightly` 브랜치를 이용할 수 있다.
좋은 생각입니다.

2021-05-05 14:54 UTC, jinsoo601 approved these changes

2021-05-06 06:24 UTC, merged