Update core-concepts.md in KOR
facebookexperimental/Recoil pull request #1005
Opened 2021-05-03 07:48 UTC by nightohl

Corrected the typo and corrected some sentences to make it more natural in Korean.

2021-05-03 21:20 UTC, jinsoo601 requested changes
PR 올려주셔서 감사합니다!

2021-05-03 21:20 UTC, jinsoo601 commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/core-concepts.md
> +Recoil을 사용하면 _atoms_ (공유 상태)에서 _selectors_ (순수 함수)를 거쳐 React 컴포넌트로 내려가는 데이터 흐름 그래프를 생성할 수 있다. Atoms는 컴포넌트가 구독할 수 있는 상태의 단위다. Selectors 는 이 atoms state를 동기 또는 비동기식으로 변환한다.
데이터 흐름 그래프에서 그래프를 빼는건 어떨까요? 영어로 쓸때는 자연스러운데 한글로 쓰니까 어색하네요. 
마지막 문장은
Selectors는 하나 이상의 atom의 값을 동기 또는 비동기 방식을 통해 새로운 값으로 변환한다.
는 어떤가요?

2021-05-03 21:20 UTC, jinsoo601 commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/core-concepts.md
> +Atoms는 상태의 단위다. 그것들은 업데이트와 구독이 가능하다. atom이 업데이트되면 각각의 구독된 컴포넌트는 새로운 값을 반영하여 다시 렌더링 된다. atoms는 런타임에서 생성될 수도 있다. Atoms는 React의 로컬 컴포넌트의 상태 대신 사용할 수 있다. 동일한 atom이 여러 컴포넌트에서 사용되는 경우 모든 컴포넌트는 상태를 공유한다.
Atoms는 상태의 단위다. 그것들은 업데이트와 구독이 가능하다 -> Atoms는 상태의 최소단위이며, 업데이트와 구독이 가능하다.

2021-05-03 21:20 UTC, jinsoo601 commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/core-concepts.md
> +Selectors는 어떤 컴포넌트가 필요한지, 어떤 상태에 의존하는지 추적하기 때문에 이러한 함수적인 접근방식을 매우 효율적으로 만든다.
Selectors는 어떤 컴포넌트가 필요한지 -> Selectors는 어떤 컴포넌트에서 사용되는지,

2021-05-03 21:20 UTC, jinsoo601 commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/core-concepts.md
> +`get` 속성은 계산될 함수다. 전달되는 `get` 인자를 통해 atoms와 다른 selectors에 접근할 수 있다. 다른 atoms나 selectors에 접근하면 자동으로 종속 관계가 생성되므로, 참조했던 다른 atoms나 selectors가 업데이트되면 이 함수도 다시 수행된다.
위에서 실행이라는 표현을 쓰셨으니까, 여기서도 수행->실행 으로 하는게 좋을듯합니다!

2021-05-03 21:20 UTC, jinsoo601 commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/core-concepts.md
> +이 `fontSizeLabelState` 예시에서 selector는 `fontSizeState` atom에 대한 하나의 의존성을 갖는다. 개념적으로 `fontSizeLabelState` selector는 `fontSizeState`를 입력으로 사용하고 형식화된 글꼴 크기 레이블을 출력으로 반환하는 순수 함수처럼 동작한다.
atom에 대한 하나의 의존성을 갖는다 -> 하나의 atom에 의존성을 갖는다.

2021-05-03 21:20 UTC, jinsoo601 commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/core-concepts.md
> +Selectors는 `useRecoilValue()`를 사용해 읽을 수 있다. `useRecoilValue()`는 하나의 atom이나 selector를 인자로 받아 대응하는 값을 반환한다. `fontSizeLabelState` selector는 writable하지 않기 때문에 `useRecoilState()`를 이용하지 않는다. (writable한 sel
를 봐라 -> 에 자세히 기술되어 있다.

2021-05-04 02:48 UTC, nightohl commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/core-concepts.md
> +Recoil을 사용하면 _atoms_ (공유 상태)에서 _selectors_ (순수 함수)를 거쳐 React 컴포넌트로 내려가는 데이터 흐름 그래프를 생성할 수 있다. Atoms는 컴포넌트가 구독할 수 있는 상태의 단위다. Selectors 는 이 atoms state를 동기 또는 비동기식으로 변환한다.
data flow graph가 쓰이는 단어다 보니 기존 해석을 그대로 가져갔는데, 
1. 데이터 흐름 그래프(DFG)를 만들 수 있다.
2. data-flow graph를 만들 수 있다.
원문의 단어 그대로 가져가는 것도 괜찮은 거 같습니다.

2021-05-04 02:50 UTC, nightohl commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/core-concepts.md
> +Recoil을 사용하면 _atoms_ (공유 상태)에서 _selectors_ (순수 함수)를 거쳐 React 컴포넌트로 내려가는 데이터 흐름 그래프를 생성할 수 있다. Atoms는 컴포넌트가 구독할 수 있는 상태의 단위다. Selectors 는 이 atoms state를 동기 또는 비동기식으로 변환한다.
Selectors는 atoms 상태값을 동기 또는 비동기 방식을 통해 변환한다.
는 어떠신가요?

2021-05-04 02:52 UTC, nightohl commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/core-concepts.md
> +Selectors는 `useRecoilValue()`를 사용해 읽을 수 있다. `useRecoilValue()`는 하나의 atom이나 selector를 인자로 받아 대응하는 값을 반환한다. `fontSizeLabelState` selector는 writable하지 않기 때문에 `useRecoilState()`를 이용하지 않는다. (writable한 sel
writable한 selectors의 더 많은 정보는 [selector API reference](/docs/api-reference/core/selector)에 자세히 기술되어 있다.
로 수정하겠습니다.

2021-05-04 02:56 UTC, nightohl commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/core-concepts.md
> +Atoms는 상태의 단위다. 그것들은 업데이트와 구독이 가능하다. atom이 업데이트되면 각각의 구독된 컴포넌트는 새로운 값을 반영하여 다시 렌더링 된다. atoms는 런타임에서 생성될 수도 있다. Atoms는 React의 로컬 컴포넌트의 상태 대신 사용할 수 있다. 동일한 atom이 여러 컴포넌트에서 사용되는 경우 모든 컴포넌트는 상태를 공유한다.
최소단위라는 표현이 맞는지는 잘 모르겠습니다.
원문에서도 문장을 연결짓지 않고 굳이 2문장으로 짧게 끊은 것이 강조를 위해 의도된 것이라고 생각했는데, "그것들은"이라는 표현이 어색하다는 점은 동감합니다..!

Atoms는 상태의 단위이며, 업데이트와 구독이 가능하다.
는 어떠신가요?

2021-05-04 03:04 UTC, nightohl commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/core-concepts.md
> +Selectors는 어떤 컴포넌트가 필요한지, 어떤 상태에 의존하는지 추적하기 때문에 이러한 함수적인 접근방식을 매우 효율적으로 만든다.
앗.. 이 문장은 제가 건너뛰었던 부분인데 어색하긴 하네요.
Selectors는 어떤 컴포넌트가 자신을 필요로하는지, 또 자신은 어떤 상태에 의존하는지를 추적하기 때문에...
는 어떠신가요?

2021-05-04 03:05 UTC, nightohl commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/core-concepts.md
> +`get` 속성은 계산될 함수다. 전달되는 `get` 인자를 통해 atoms와 다른 selectors에 접근할 수 있다. 다른 atoms나 selectors에 접근하면 자동으로 종속 관계가 생성되므로, 참조했던 다른 atoms나 selectors가 업데이트되면 이 함수도 다시 수행된다.
수정하겠습니다.

2021-05-04 03:06 UTC, nightohl commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/core-concepts.md
> +이 `fontSizeLabelState` 예시에서 selector는 `fontSizeState` atom에 대한 하나의 의존성을 갖는다. 개념적으로 `fontSizeLabelState` selector는 `fontSizeState`를 입력으로 사용하고 형식화된 글꼴 크기 레이블을 출력으로 반환하는 순수 함수처럼 동작한다.
예시에서 selector는 `fontSizeState`라는 하나의 atom에 의존성을 갖는다.
는 어떠신가요?

2021-05-04 15:11 UTC, jinsoo601 commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/core-concepts.md
> +Recoil을 사용하면 _atoms_ (공유 상태)에서 _selectors_ (순수 함수)를 거쳐 React 컴포넌트로 내려가는 데이터 흐름 그래프를 생성할 수 있다. Atoms는 컴포넌트가 구독할 수 있는 상태의 단위다. Selectors 는 이 atoms state를 동기 또는 비동기식으로 변환한다.
1. 원문 단어 그대로 가져가는거 좋은거 같습니다.
2. 좋습니다!

2021-05-04 15:11 UTC, jinsoo601 commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/core-concepts.md
> +Atoms는 상태의 단위다. 그것들은 업데이트와 구독이 가능하다. atom이 업데이트되면 각각의 구독된 컴포넌트는 새로운 값을 반영하여 다시 렌더링 된다. atoms는 런타임에서 생성될 수도 있다. Atoms는 React의 로컬 컴포넌트의 상태 대신 사용할 수 있다. 동일한 atom이 여러 컴포넌트에서 사용되는 경우 모든 컴포넌트는 상태를 공유한다.
좋습니다!

2021-05-04 15:12 UTC, jinsoo601 commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/core-concepts.md
> +Selectors는 어떤 컴포넌트가 필요한지, 어떤 상태에 의존하는지 추적하기 때문에 이러한 함수적인 접근방식을 매우 효율적으로 만든다.
좋습니다!

2021-05-04 15:19 UTC, jinsoo601 commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/core-concepts.md
> +이 `fontSizeLabelState` 예시에서 selector는 `fontSizeState` atom에 대한 하나의 의존성을 갖는다. 개념적으로 `fontSizeLabelState` selector는 `fontSizeState`를 입력으로 사용하고 형식화된 글꼴 크기 레이블을 출력으로 반환하는 순수 함수처럼 동작한다.
좋습니다!

2021-05-05 14:54 UTC, jinsoo601 approved these changes

2021-05-06 06:23 UTC, merged