Update RecoilRootProps type for React 18 types
facebookexperimental/Recoil pull request #1718
Opened 2022-04-08 03:55 UTC by dqn

Since @types/react v18, Implicit `children` was removed from `React.FC`. This change works for @types/react v18 and earlier.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210

2022-04-08 19:10 UTC, mondaychen requested changes

2022-04-08 19:10 UTC, mondaychen commented on typescript/index.d.ts
> +  children?: React.ReactNode | undefined,
Let's use this opportunity to make it required and align with the Flow type https://github.com/facebookexperimental/Recoil/blob/main/packages/recoil/core/Recoil_RecoilRoot.js#L66

```suggestion
  children: React.ReactNode,
```

(also I think `undefined` is included in `React.ReactNode`)

2022-04-09 15:05 UTC, dqn commented
@mondaychen Thank you for reviewing! I fixed that.

2022-04-09 19:02 UTC, mondaychen commented
Can you help fix the tests? https://github.com/facebookexperimental/Recoil/blob/main/typescript/tests.ts

2022-04-10 11:19 UTC, dqn commented
Fixed.

2022-04-11 15:06 UTC, dqn commented on typescript/tests.ts
> +import React = require('react');
We can use default import by adding the compilerOptions `esModuleInterop: true`, but I use namespace import because I found it used in other files.

2022-04-11 15:07 UTC, mondaychen approved these changes

2022-04-11 15:14 UTC, dqn commented on typescript/tests.ts
> +import React = require('react');
Note: `import = require()` is a valid syntax for importing modules exported with `export = `.
https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require

2022-04-12 01:28 UTC, closed without merging