fix: pass CI tests
facebookexperimental/Recoil pull request #555
Opened 2020-09-05 05:22 UTC by mallchel

2020-09-05 15:31 UTC, mallchel commented
@aaronabramov 
console error prevents success github actions workflow. This PR is just setting up running CI tests, mocking console.error and console.warn

2020-09-08 23:52 UTC, drarmstr commented
cc @aaronabramov

2020-09-09 06:06 UTC, mallchel commented
@drarmstr it seems like tests were failing only in this line ```expect(c.textContent).toBe('"ATOMATOMATOM"');```
We can remove mocks for console.error and console.warn for CI

2020-09-09 07:55 UTC, drarmstr commented
> @drarmstr it seems like tests were failing only in this line `expect(c.textContent).toBe('"ATOMATOMATOM"');`
> We can remove mocks for console.error and console.warn for CI

If tests are failing there, could it be an actual failure or test we want to fix?  This PR seems dangerous to hide problems?

2020-09-09 10:53 UTC, mallchel commented
@drarmstr No, this PR doesn't hide failed tests. If some test fails with the "expect" expression, then the exit code would be non zero and GitHub's actions fail.

Mocking for console methods doesn't make sense at the moment. I can just remove it together with the test-ci script. What do you think?

2020-09-09 20:06 UTC, drarmstr commented
I see.  I also fixed the `act()` issue with our local version of #561 (not currently visible on GitHub, the public PR isn't valid).  Anyway, I'll leave this for @aaronabramov to update when he returns next week.

2020-09-15 06:52 UTC, mallchel commented
@aaronabramov I'm not sure how to properly test the useRecoilValueLoadable

2020-09-15 18:30 UTC, drarmstr requested changes

2020-09-15 18:30 UTC, drarmstr commented on src/recoil_values/__tests__/Recoil_selector-test.js
> +    await act(flushPromisesAndTimers);
These are no longer necessary with #576

2020-09-16 05:41 UTC, mallchel commented on src/recoil_values/__tests__/Recoil_selector-test.js
> +    await act(flushPromisesAndTimers);
@drarmstr Yeah. I missed it. fixed

2020-09-16 20:42 UTC, aaronabramov commented on src/util/Recoil_mutableSource.js
> +function mutableSourceIsExist() {
```js
function mutableSourceExists() {
```

2020-09-17 07:11 UTC, mallchel commented
@aaronabramov updated a PR, moved useMutableSource to Recoil_mutableSource.

2020-09-17 19:09 UTC, closed without merging